export const ENTERPRISE_CONFIG = {
    GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID",
    WHATSAPP: {
        ACCESS_TOKEN: "YOUR_WHATSAPP_ACCESS_TOKEN",
        PHONE_NUMBER_ID: "YOUR_PHONE_NUMBER_ID",
        BUSINESS_ACCOUNT_ID: "YOUR_BUSINESS_ACCOUNT_ID",
        DEFAULT_RECIPIENT: "YOUR_PHONE_NUMBER"
    },
    OPENWEATHER_KEY: "YOUR_OPENWEATHER_API_KEY"
};
